title = "Infuse"

defaultContentLanguage = "en"
languageCode = "en-us"
defaultContentLanguageInSubdir = true

rssLimit  = 300

archetypeDir = "archetypes"
contentDir   = "content"
dataDir      = "data"
layoutDir    = "layouts"
publishDir   = "public"

buildDrafts  = false
buildFuture  = false
buildExpored = false
canonifyURLs = true

enableRobotsTXT = true
enableGitInfo   = false
enableEmoji     = true
enableMissingTranslationPlaceholders = true
disableRSS     = false
disableSitemap = false
disable404     = false
disableHugoGeneratorInject = true

pluralizeListTitles = false

[permalinks]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true

[taxonomies]
  category = "categories"
  tag = "tags"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Metadata mostly used in document's head
  description = ""
  keywords = ""
  images = ["media/images/thumbnail.png"]

  # Prefix of link to the git commit detail page. GitInfo must be enabled.
  gitUrl = "https://github.com/x/y/commit/"

  # Integrate Javascript files or stylesheets by adding the url to the external assets or by
  # linking local files with their path relative to the static folder, e.g. "css/styles.css"
  customCSS = []
  customJS  = []

  # Colors for favicons
  [params.favicon.color]
    mask = "#194E80"
    msapplication = "#194E80"

  # Social icons
  [[params.social]]
    name = "github"
    url  = "https://github.com/"

  [[params.social]]
    name = "twitter"
    url  = "https://twitter.com/"
  
  [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/products/x/"

[languages]
  [languages.en]
  weight    = 1
  contentDir = "content/en"
  [languages.en.params]
    languageName = "English"
  [[languages.en.menu.main]]
    identifier = "learning-paths"
    name       = "Learning Paths"
    url        = "/learning-paths/"
    weight     = "1"
  [[languages.en.menu.main]]
    identifier = "badges"
    name       = "Badges"
    url        = "/badges/"
    weight     = "2"

  [languages.de]
  weight    = 2
  contentDir = "content/de"
  [languages.de.params]
    languageName = "Deutsch"
  [[languages.de.menu.main]]
    identifier = "learning-paths"
    name       = "Learning Paths"
    url        = "/learning-paths/"
    weight     = "1"
  [[languages.de.menu.main]]
    identifier = "badges"
    name       = "Badges"
    url        = "/badges/"
    weight     = "2"

[privacy]
  [privacy.instagram]
    disable = false
    simple = true
  [privacy.twitter]
    disable = false
    enableDNT = true
    simple = false
  [privacy.vimeo]
    disable = false
    enableDNT = true
    simple = false
  [privacy.youtube]
    disable = false
    privacyEnhanced = true
