locale: "en"
logo_url: ./cms-logo.svg

site_url: http://localhost:1313
display_url: http://localhost:1313

backend:
  name: git-gateway
  # repo: OpenInternet/infuse
  # branch: main

local_backend: true

publish_mode: editorial_workflow
media_folder: static/media/uploads
public_folder: /media/uploads

i18n:
  # Required and can be one of multiple_folders, multiple_files or single_file
  # multiple_folders - persists files in `<folder>/<locale>/<slug>.<extension>`
  # multiple_files - persists files in `<folder>/<slug>.<locale>.<extension>`
  # single_file - persists a single file in `<folder>/<slug>.<extension>`
  structure: multiple_files

  # Required - a list of locales to show in the editor UI
  locales: [en, es, fr, ar]

  # Optional, defaults to the first item in locales.
  # The locale to be used for fields validation and as a baseline for the entry.
  default_locale: en

slug:
  encoding: "ascii"
  clean_accents: true

collections:
  - name: "learning_paths"
    label: "Learning Paths"
    folder: "content/learning-path"
    identifier_field: "{{ title }}"
    create: true
    delete: true
    i18n: true
    nested:
      depth: 2
      # summary: "{{title}}"
    fields:
      - name: "title"
        label: "Title"
        widget: "string"
      - name: "body"
        label: "Body"
        widget: "markdown"
    # filters:
    #   fileType: "md"
    #   exclude:
    #     - "_index.md"
    # filter:
    #   field: "type"
    #   value: "learning-path"
  - name: "learning_path_2"
    label: "Learning Path 2"
    folder: "content/learning-path/2"
    identifier_field: "title"
    create: true
    delete: true
    i18n: true
    fields:
      - name: "title"
        label: "Title"
        widget: "string"
      - name: "body"
        label: "Body"
        widget: "markdown"
  - name: "badges"
    label: "Badges"
    folder: "content/badges"
    identifier_field: "title"
    i18n: true
    fields:
      - name: "title"
        label: "Title"
        widget: "string"
  - name: pages
    label: Pages
    folder: "content"
    i18n: true
    fields:
      - name: "title"
        label: "Title"
        widget: "string"
      - name: "weight"
        label: "Order"
        widget: "number"
        required: false
      - name: "navbar"
        label: "Is in navbar"
        widget: "boolean"
        default: false
        required: false
      - name: "body"
        label: "Body"
        widget: "markdown"
        required: false
  - name: "faq"
    label: "Frequently Asked Questions"
    folder: "data"
    format: "yaml"
    create: true
    delete: true
    i18n: true
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
        default: "FAQ"
      - label: "Items"
        name: "items"
        widget: "list"
        fields:
          - label: "Question"
            name: "question"
            widget: "string"
            i18n: true
          - label: "Answer"
            name: "answer"
            widget: "text"
            i18n: true
  - name: "i18n-keys"
    label: "UI translation"
    folder: "i18n"
    format: "toml"
    create: false
    slug: "{{locale}}"
    fields:
      - label: "Content"
        name: "content"
        widget: "text"
        required: false