locale: "en"
logo_url: ./cms-logo.svg

site_url: http://localhost:1313
display_url: http://localhost:1313

backend:
  name: git-gateway
  # repo: OpenInternet/saferjourno
  # branch: main

local_backend: true

publish_mode: editorial_workflow
media_folder: static/media/uploads
public_folder: /media/uploads

i18n:
  # Required and can be one of multiple_folders, multiple_files or single_file
  # multiple_folders - persists files in `<folder>/<locale>/<slug>.<extension>`
  # multiple_files - persists files in `<folder>/<slug>.<locale>.<extension>`
  # single_file - persists a single file in `<folder>/<slug>.<extension>`
  structure: multiple_folders

  # Required - a list of locales to show in the editor UI
  locales: [en, fr]

  # Optional, defaults to the first item in locales.
  # The locale to be used for fields validation and as a baseline for the entry.
  default_locale: en

slug:
  encoding: "ascii"
  clean_accents: true

collections:
  - name: "en_learning_path"
    label: "Learning Paths (English)"
    folder: "content/en/learning-path"
    identifier_field: "title"
    create: true
    delete: true
    nested:
      depth: 2
      summary: "{{title}}"
    fields:
      - name: "title"
        label: "Title"
        widget: "string"
      - name: "body"
        label: "Body"
        widget: "markdown"
    filters:
      fileType: "md"
      exclude:
        - "_index.md"
    preview_path_date_field: "updated_on"
    filter:
      field: "type"
      value: "learning-path"